declare module "element-ui";
declare module "element-ui/lib/locale";
declare module "element-ui/lib/locale/lang/ja";
declare module "element-ui/lib/transitions/collapse-transition";
declare module "@aws-amplify/ui";
declare module "aws-amplify-vue";
declare module "@/aws-exports.js";
declare module "vuedraggable";
declare module "uuid/v4";
